//  PrivateURLs.java
//
//  `bundle install`
//  `./appkeeper.sh yonghuitest`
//
//  Created by lijunjie on 16/06/02.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghuitest]
// automatic generated by app_keeper.rb
package com.intfocus.yonghuitest.util;

public class PrivateURLs {
  public final static String kAppCode         = "yonghuitest";
  public final static String kThemeColor      = "#53a93f";
  public final static String kBannerBgColor   = "#53a93f";
  public final static String kBannerTextColor = "#ffffff";
  public final static String kInitPassword    = "123456";

  public final static String kBaseUrl      = "https://development.shengyiplus.com";
  public final static String kBaseUrl1     = "http://10.0.3.2:4567";

  public final static String kPgyerAppId   = "a0fb26faac52207f08129f092274f8c6";
  public final static String kPgyerUrl     = "http://www.pgyer.com/yh-test-a";

  public final static String kUMAppId      = "57b5224467e58e3e9b001fc2";
  public final static String kWXAppId      = "wxcff211a335b17088";
  public final static String kWXAppSecret  = "af964fd476b59bf54682bb15f23a0569";

  public final static boolean kDashboardAd      = false;
  public final static boolean kDropMenuScan     = true;
  public final static boolean kDropMenuSearch   = true;
  public final static boolean kDropMenuVoice    = true;
  public final static boolean kDropMenuUserInfo = true;

  public final static boolean kTabBar        = true;
  public final static boolean kTabBarKPI     = true;
  public final static boolean kTabBarAnalyse = true;
  public final static boolean kTabBarApp     = true;
  public final static boolean kTabBarMessage = true;

  public final static boolean kSubjectComment = true;
  public final static boolean kSubjectShare   = true;
}
