//  PrivateURLs.java
//
//  `bundle install`
//  `./appkeeper.sh shengyiplus`
//
//  Created by lijunjie on 16/06/02.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [shengyiplus]
// automatic generated by app_keeper.rb
package com.intfocus.hdmcre.util;

public class PrivateURLs {
  public final static String kAppCode         = "shengyiplus";
  public final static String kThemeColor      = "#8C0122";
  public final static String kBannerBgColor   = "#53a93f";
  public final static String kBannerTextColor = "#ffffff";
  public final static String kInitPassword    = "123456";

//  public final static String kBaseUrl = "http://123.56.91.131:8090";
  public final static String kBaseUrl = "http://123.56.91.131:8090";

  public final static String kPgyerAppId   = "38e630134f0ca8098aeffe13d52ad5b6";
  public final static String kPgyerUrl     = "https://www.pgyer.com/hdmcre-a";

  public final static String kUMAppId      = "5705c952e0f55a391a0011cc";
  public final static String kWXAppId      = "wx0ad40e5c84419ce2";
  public final static String kWXAppSecret  = "fac49cd8a126145d7b0bd528306298d8";

  public final static boolean kDashboardAd      = true;
  public final static boolean kDropMenuScan     = true;
  public final static boolean kDropMenuSearch   = true;
  public final static boolean kDropMenuVoice    = true;
  public final static boolean kDropMenuUserInfo = true;

  public final static boolean kTabBar        = true;
  public final static boolean kTabBarKPI     = true;
  public final static boolean kTabBarAnalyse = true;
  public final static boolean kTabBarApp     = true;
  public final static boolean kTabBarMessage = true;

  public final static boolean kSubjectComment = true;
  public final static boolean kSubjectShare   = true;
}
